### ISSUE TITLE
Linear() 函数未定义

### ISSUE THREAD

**Issue by baisechundu** [YujieOuO/PSTL#1]
procedure.py 文件中 103 行 self.classifier = Linear().cuda()，其中 Linear() 未找到相关定义. 应该是一个线性分类器，类似 nn.Linear(hidden_dim, num_class)，不知道我的理解对吗？

**Comment by YujieOuO** [comment]
是的，linear()指代单层的线性分类器，参数随数据集类别个数变化。方便起见已经加上去了，感谢~
