### ISSUE TITLE
Pre-Trained Model Weights

### ISSUE THREAD

**Issue by Zepharchit** [YujieOuO/PSTL#2]
Hi, 
Thank you for the interesting paper and repository.
Requesting to add the pre-trained model weights to the repository.

**Comment by YujieOuO** [comment]
Hello, thank you for your attention. Due to the small amount of data in the skeleton dataset, the time required for pretraining is not extensive (approximately 6 hours with a single GPU). Therefore, you can try pretraining and obtaining the weights on your own. Actually, the final results obtained from this repository can be slightly higher than those mentioned in our paper. If needed, we can also provide pretrained weights in the future.

**Comment by peymosiec01** [comment]
Hi @YujieOuO 
How did you use the pre-trained/finetuned model weights to train your new PSTL/st_gcn model?
I need help finding an entry point (main.py) to run the model.
Thanks.

**Comment by YujieOuO** [comment]
> Hi @YujieOuO How did you use the pre-trained/finetuned model weights to train your new PSTL/st_gcn model? I need help finding an entry point (main.py) to run the model. Thanks.

sorry, the current code does not support it. If you want to use pre-trained weights for re pre-training, you can simply rewrite the self.load_weights function in the BTProcessor section. Usually, we use the pre-trained weights for downstream tasks, such as [python procedure.py with 'train_mode="finetune"']

**Comment by peymosiec01** [comment]
> > Hi @YujieOuO How did you use the pre-trained/finetuned model weights to train your new PSTL/st_gcn model? I need help finding an entry point (main.py) to run the model. Thanks.
> 
> sorry, the current code does not support it. If you want to use pre-trained weights for re pre-training, you can simply rewrite the self.load_weights function in the BTProcessor section. Usually, we use the pre-trained weights for downstream tasks, such as [python procedure.py with 'train_mode="finetune"']

Thank you for the clarification.

**Comment by peymosiec01** [comment]
@YujieOuO Is there a way to test different hyperparameters easily like the GridSearchCV ?

**Comment by YujieOuO** [comment]
> @YujieOuO Is there a way to test different hyperparameters easily like the GridSearchCV ?


We didn't invest significant effort in hyperparameter; in fact, the same  parameters was used for all experiments and datasets. If you intend to perform a grid search for multi-stream fusion, you might find guidance in the following repository: https://github.com/paolomandica/HYSP/tree/main/src/ensemble
