### ISSUE TITLE
Linear evaluation not working properly

### ISSUE THREAD

**Issue by atifshahcs** [YujieOuO/PSTL#3]
Hello, thank you for providing your code.
The linear evaluation code not working properly and there are some missing parameters: 
Got this error: test_epoch is missing value(s): ['result_path', 'label_path']

Thanks,

**Comment by YujieOuO** [comment]
Hi, the result_path and label_path are custom locations for storing the output results. You can set them according to different environments. For convenience, I have added example paths. Actually，even if the output results are not saved, they will still be displayed in the terminal.
